alter

diff --git a/steps/update-oidc-issuer-url.yaml b/steps/update-oidc-issuer-url.yaml
--- a/steps/update-oidc-issuer-url.yaml
+++ b/steps/update-oidc-issuer-url.yaml
@@ -27,19 +27,6 @@ parameters:
     type: string
 
 steps:
-- ${{ if ne(parameters.cluster, 'All') }}:
-  - task: AzureCLI@2
-    displayName: 'Get AKS OIDC Issuer URL'
-    inputs:
-      azureSubscription: ${{ parameters.serviceConnection }}
-      scriptType: bash
-      scriptLocation: inlineScript
-      inlineScript: |
-        echo "##vso[task.setvariable variable=AKS_ISSUER_URL]$(az aks show \
-          -n ${{ parameters.clusterPrefix }}-${{ parameters.environment }}-${{ parameters.cluster }}-aks \
-          -g ${{ parameters.clusterPrefix }}-${{ parameters.environment }}-${{ parameters.cluster }}-rg \
-          --query "oidcIssuerProfile.issuerUrl" -otsv)"
-
 - task: AzureKeyVault@1
   displayName: 'Get OIDC issuer URL git token from Keyvault'
   inputs:
@@ -47,49 +34,59 @@ steps:
     keyVaultName: ${{ parameters.keyvaultName }}
     secretsFilter: ${{ parameters.gitTokenSecret }}
 
-- task: Bash@3
+- task: AzureCLI@2
   displayName: 'Update OIDC Issuer URL in flux-config'
   env:
-    ISSUER_URL: $(AKS_ISSUER_URL)
     GIT_TOKEN: $(${{ parameters.gitTokenSecret }})
   inputs:
-    targetType: inline
-    workingDirectory: $(Pipeline.Workspace)/s
-    script: |
-        set -e
+    azureSubscription: ${{ parameters.serviceConnection }}
+    scriptType: bash
+    scriptLocation: inlineScript
+    workingDirectory: $(Pipeline.Workspace)/s/${{ parameters.fluxConfigRepo }}
+    inlineScript: |
+      set -e
 
-        ENV="${{ parameters.environment }}"
-        CLUSTER="${{ parameters.cluster }}"
-        REPO="${{ parameters.fluxConfigRepo }}"
-        FLUX_ENV="${{ parameters.fluxConfigEnvironment }}"
+      ENV="${{ parameters.environment }}"
+      CLUSTER="${{ parameters.cluster }}"
+      FLUX_ENV="${{ parameters.fluxConfigEnvironment }}"
 
-        cd "$REPO"
+      if [ -z "$FLUX_ENV" ]; then
+        FLUX_ENV=$([[ "$ENV" == "ptl" ]] && echo "ptl-intsvc" || ([[ "$ENV" == "ptlsbox" ]] && echo "sbox-intsvc" || echo "$ENV"))
+      fi
+
+      if [ "$CLUSTER" == "All" ]; then
+        cluster_numbers=$(az aks list --output tsv --query '[].name' | sed -n "s/${{ parameters.clusterPrefix }}-${ENV}-\([0-9][0-9]\)-aks/\1/p")
+      else
+        cluster_numbers="$CLUSTER"
+      fi
+
+      for c in $cluster_numbers; do
+        ISSUER_URL=$(az aks show \
+          -n ${{ parameters.clusterPrefix }}-${ENV}-${c}-aks \
+          -g ${{ parameters.clusterPrefix }}-${ENV}-${c}-rg \
+          --query "oidcIssuerProfile.issuerUrl" -otsv)
 
         if [ -n "$ISSUER_URL" ]; then
-          echo "Issuer URL is: ${ISSUER_URL}"
-
-          if [ -z "$FLUX_ENV" ]; then
-            FLUX_ENV=$([[ "$ENV" == "ptl" ]] && echo "ptl-intsvc" || ([[ "$ENV" == "ptlsbox" ]] && echo "sbox-intsvc" || echo "$ENV"))
-          fi
-
-          file_path="apps/flux-system/${FLUX_ENV}/${CLUSTER}/kustomize.yaml"
+          echo "Issuer URL for cluster ${c}: ${ISSUER_URL}"
+          file_path="apps/flux-system/${FLUX_ENV}/${c}/kustomize.yaml"
           sed -i -e "s/ISSUER_URL:.*/ISSUER_URL: \"$(echo "$ISSUER_URL" | sed 's/[\/&]/\\&/g')\"/g" "$file_path"
-
-          if [[ -n $(git status -s) ]]; then
-            git diff .
-            git config --global user.email github-platform-operations@HMCTS.NET
-            git config --global user.name "hmcts-platform-operations"
-            git add .
-            git commit -m "Updating OIDC Issuer URL for $CLUSTER cluster in $FLUX_ENV"
-            git remote set-url origin "https://hmcts-platform-operations:${GIT_TOKEN}@github.com/hmcts/${REPO}.git"
-            git pull origin master --rebase
-            for i in {1..5}; do
-              git push --set-upstream origin HEAD:master && break || {
-                echo "Failed to push, attempt $i of 5 - pulling remote again"
-                git pull origin master --rebase
-              }
-            done
-          else
-            echo "No change to issuer URL, skipping git push..."
-          fi
         fi
+      done
+
+      if [[ -n $(git status -s) ]]; then
+        git diff .
+        git config --global user.email github-platform-operations@HMCTS.NET
+        git config --global user.name "hmcts-platform-operations"
+        git add .
+        git commit -m "Updating OIDC Issuer URL for $CLUSTER cluster(s) in $FLUX_ENV"
+        git remote set-url origin "https://hmcts-platform-operations:${GIT_TOKEN}@github.com/hmcts/${{ parameters.fluxConfigRepo }}.git"
+        git pull origin master --rebase
+        for i in {1..5}; do
+          git push --set-upstream origin HEAD:master && break || {
+            echo "Failed to push, attempt $i of 5 - pulling remote again"
+            git pull origin master --rebase
+          }
+        done
+      else
+        echo "No change to issuer URL, skipping git push..."
+      fi
